<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\BRT.sav" />
    <None Remove="Resources\EoS.sav" />
    <None Remove="Resources\EoT.sav" />
    <None Remove="Resources\RRT.sav" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BRT.sav" />
    <EmbeddedResource Include="Resources\EoS.sav" />
    <EmbeddedResource Include="Resources\EoT.sav" />
    <EmbeddedResource Include="Resources\RRT.sav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SkyEditor.SaveEditor\SkyEditor.SaveEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
