<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SkyEditor.SaveEditor.Cli</RootNamespace>
    <AssemblyName>ske</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyEditor.SaveEditor\SkyEditor.SaveEditor.csproj" />
  </ItemGroup>

</Project>
