// AUTO-GENERATED -- do not hand-edit.
// Item ID -> icon filename (under Assets/Items/), joined from RBItems.txt against
// ../samlowedotdev's wondermail-item-icons.js (sourced from mysterydungeonwiki.com,
// CC BY-NC-SA per that wiki's license footer), plus a handful of manual fixes for
// items missing from that mapping but sharing an obvious in-game sprite with a
// covered sibling (e.g. every other "* Orb" item all use the same generic orb icon).
using System.Collections.Generic;

namespace SkyEditor.SaveEditor.Gui;

internal static class ItemIcons
{
    public static readonly IReadOnlyDictionary<int, string> IconFileByItemId = new Dictionary<int, string>
    {
        [1] = "stick.png", // Stick
        [2] = "iron-thorn.png", // Iron Thorn
        [3] = "silver-spike.png", // Silver Spike
        [4] = "gold-fang.png", // Gold Fang
        [5] = "cacnea-spike.png", // Cacnea Spike
        [6] = "corsola-twig.png", // Corsola Twig
        [7] = "gravelerock.png", // Gravelerock
        [8] = "geo-pebble.png", // Geo Pebble
        [9] = "scarf.png", // Mobile Scarf
        [10] = "scarf.png", // Heal Ribbon
        [11] = "scarf.png", // Twist Band
        [12] = "glasses.png", // Scope Lens
        [13] = "scarf.png", // Patsy Band
        [14] = "scarf.png", // No-Stick Cap
        [15] = "scarf.png", // Pierce Band
        [16] = "scarf.png", // Joy Ribbon
        [17] = "glasses.png", // X-Ray Specs
        [18] = "scarf.png", // Persim Band
        [19] = "scarf.png", // Power Band
        [20] = "scarf.png", // Pecha Scarf
        [21] = "glasses.png", // Insomniscope
        [22] = "scarf.png", // Warp Scarf
        [23] = "scarf.png", // Tight Belt
        [24] = "scarf.png", // Sneak Scarf
        [25] = "scarf.png", // Gold Ribbon
        [26] = "glasses.png", // Goggle Specs
        [27] = "scarf.png", // Diet Ribbon
        [28] = "scarf.png", // Trap Scarf
        [29] = "scarf.png", // Racket Band
        [30] = "scarf.png", // Def. Scarf
        [31] = "scarf.png", // Stamina Band
        [32] = "scarf.png", // Plain Ribbon
        [33] = "scarf.png", // Special Band
        [34] = "scarf.png", // Zinc Band
        [35] = "scarf.png", // Detect Band
        [36] = "glasses.png", // Alert Specs
        [37] = "scarf.png", // Dodge Scarf
        [38] = "scarf.png", // Bounce Band
        [39] = "scarf.png", // Curve Band
        [40] = "glasses.png", // Whiff Specs
        [41] = "glasses.png", // No-Aim Scope
        [42] = "glasses.png", // Lockon Specs
        [43] = "scarf.png", // Munch Belt
        [44] = "scarf.png", // Pass Scarf
        [45] = "scarf.png", // Weather Band
        [46] = "scarf.png", // Friend Bow
        [47] = "beauty-scarf.png", // Beauty Scarf
        [48] = "sun-ribbon.png", // Sun Ribbon
        [49] = "lunar-ribbon.png", // Lunar Ribbon
        [53] = "seed.png", // Heal Seed
        [54] = "wish-stone.png", // Wish Stone
        [55] = "oran-berry.png", // Oran Berry
        [56] = "sitrus-berry.png", // Sitrus Berry
        [57] = "seed.png", // Eyedrop Seed
        [58] = "seed.png", // Reviver Seed
        [59] = "seed.png", // Blinker Seed
        [60] = "seed.png", // Doom Seed
        [61] = "seed.png", // Allure Seed
        [62] = "seed.png", // Life Seed
        [63] = "rawst-berry.png", // Rawst Berry
        [64] = "seed.png", // Hunger Seed
        [65] = "seed.png", // Quick Seed
        [66] = "pecha-berry.png", // Pecha Berry
        [67] = "cheri-berry.png", // Cheri Berry
        [68] = "seed.png", // Totter Seed
        [69] = "seed.png", // Sleep Seed
        [70] = "seed.png", // Plain Seed
        [71] = "seed.png", // Warp Seed
        [72] = "seed.png", // Blast Seed
        [73] = "health-drink.png", // Ginseng
        [74] = "seed.png", // Joy Seed
        [75] = "chesto-berry.png", // Chesto Berry
        [76] = "seed.png", // Stun Seed
        [77] = "health-drink.png", // Max Elixir
        [78] = "health-drink.png", // Protein
        [79] = "health-drink.png", // Calcium
        [80] = "health-drink.png", // Iron
        [81] = "health-drink.png", // Zinc
        [82] = "apple.png", // Apple
        [83] = "apple.png", // Big Apple
        [84] = "grimy-food.png", // Grimy Food
        [85] = "apple.png", // Huge Apple
        [86] = "white-gummi.png", // White Gummi
        [87] = "red-gummi.png", // Red Gummi
        [88] = "blue-gummi.png", // Blue Gummi
        [89] = "clear-gummi.png", // Grass Gummi
        [90] = "clear-gummi.png", // Yellow Gummi
        [91] = "clear-gummi.png", // Clear Gummi
        [92] = "orange-gummi.png", // Orange Gummi
        [93] = "pink-gummi.png", // Pink Gummi
        [94] = "brown-gummi.png", // Brown Gummi
        [95] = "blue-gummi.png", // Sky Gummi
        [96] = "gold-gummi.png", // Gold Gummi
        [97] = "green-gummi.png", // Green Gummi
        [98] = "clear-gummi.png", // Gray Gummi
        [99] = "purple-gummi.png", // Purple Gummi
        [100] = "black-gummi.png", // Royal Gummi
        [101] = "black-gummi.png", // Black Gummi
        [102] = "clear-gummi.png", // Silver Gummi
        [103] = "banana.png", // Banana
        [104] = "chestnut.png", // Chestnut
        [106] = "upgrade.png", // Upgrade
        [108] = "thunder-sun-stone.png", // Thunderstone
        [109] = "deepseascale.png", // Deepseascale
        [110] = "deepseatooth.png", // Deepseatooth
        [111] = "thunder-sun-stone.png", // Sun Stone
        [112] = "moon-stone.png", // Moon Stone
        [113] = "fire-stone.png", // Fire Stone
        [114] = "water-stone.png", // Water Stone
        [115] = "metal-coat.png", // Metal Coat
        [116] = "leaf-stone.png", // Leaf Stone
        [117] = "dragon-scale.png", // Dragon Scale
        [118] = "link-cable.png", // Link Cable
        [119] = "ice-part.png", // Ice Part
        [120] = "steel-part.png", // Steel Part
        [121] = "rock-part.png", // Rock Part
        [122] = "music-box.png", // Music Box
        [123] = "key.png", // Key
        [124] = "tm.png", // Used TM
        [125] = "tm.png", // Focus Punch
        [126] = "tm.png", // Dragon Claw
        [127] = "tm.png", // Water Pulse
        [128] = "tm.png", // Calm Mind
        [129] = "tm.png", // Roar
        [130] = "tm.png", // Toxic
        [131] = "wonder-orb.png", // Hail Orb
        [132] = "tm.png", // Bulk Up
        [133] = "tm.png", // Bullet Seed
        [134] = "tm.png", // Hidden Power
        [135] = "wonder-orb.png", // Sunny Orb
        [136] = "tm.png", // Taunt
        [137] = "tm.png", // Ice Beam
        [138] = "tm.png", // Blizzard
        [139] = "tm.png", // Hyper Beam
        [140] = "tm.png", // Light Screen
        [141] = "tm.png", // Protect
        [142] = "wonder-orb.png", // Rainy Orb
        [143] = "tm.png", // Giga Drain
        [144] = "tm.png", // Safeguard
        [145] = "tm.png", // Frustration
        [146] = "tm.png", // Solarbeam
        [147] = "tm.png", // Iron Tail
        [148] = "tm.png", // Thunderbolt
        [149] = "tm.png", // Thunder
        [150] = "tm.png", // Earthquake
        [151] = "tm.png", // Return
        [152] = "tm.png", // Dig
        [153] = "tm.png", // Psychic
        [154] = "tm.png", // Shadow Ball
        [155] = "tm.png", // Brick Break
        [156] = "wonder-orb.png", // Evasion Orb
        [157] = "tm.png", // Reflect
        [158] = "tm.png", // Shock Wave
        [159] = "tm.png", // Flamethrower
        [160] = "tm.png", // Sludge Bomb
        [161] = "wonder-orb.png", // Sandy Orb
        [162] = "tm.png", // Fire Blast
        [163] = "wonder-orb.png", // Rocky Orb
        [164] = "tm.png", // Aerial Ace
        [165] = "tm.png", // Torment
        [166] = "tm.png", // Facade
        [167] = "tm.png", // Secret Power
        [168] = "tm.png", // Rest
        [169] = "tm.png", // Attract
        [170] = "tm.png", // Thief
        [171] = "tm.png", // Steel Wing
        [172] = "tm.png", // Skill Swap
        [173] = "wonder-orb.png", // Snatch Orb
        [174] = "tm.png", // Overheat
        [175] = "tm.png", // Wide Slash
        [176] = "tm.png", // Excavate
        [177] = "tm.png", // Spin Slash
        [178] = "wonder-orb.png", // See-Trap Orb
        [179] = "wonder-orb.png", // Mug Orb
        [180] = "wonder-orb.png", // Rebound Orb
        [181] = "wonder-orb.png", // Lob Orb
        [182] = "wonder-orb.png", // Switcher Orb
        [183] = "wonder-orb.png", // Blowback Orb
        [184] = "wonder-orb.png", // Warp Orb
        [185] = "wonder-orb.png", // Transfer Orb
        [186] = "wonder-orb.png", // Slow Orb
        [187] = "wonder-orb.png", // Quick Orb
        [188] = "wonder-orb.png", // Luminous Orb
        [189] = "wonder-orb.png", // Petrify Orb
        [190] = "wonder-orb.png", // Stayaway Orb
        [191] = "wonder-orb.png", // Pounce Orb
        [192] = "wonder-orb.png", // Trawl Orb
        [193] = "wonder-orb.png", // Cleanse Orb
        [194] = "wonder-orb.png", // Observer Orb
        [195] = "wonder-orb.png", // Decoy Orb
        [196] = "wonder-orb.png", // Slumber Orb
        [197] = "wonder-orb.png", // Totter Orb
        [198] = "wonder-orb.png", // Two-Edge Orb
        [199] = "wonder-orb.png", // Silence Orb
        [200] = "wonder-orb.png", // Escape Orb
        [201] = "wonder-orb.png", // Scanner Orb
        [202] = "wonder-orb.png", // Radar Orb
        [203] = "wonder-orb.png", // Drought Orb
        [204] = "wonder-orb.png", // Trapbust Orb
        [205] = "wonder-orb.png", // Rollcall Orb
        [206] = "wonder-orb.png", // Invisify Orb
        [207] = "wonder-orb.png", // One-Shot Orb
        [208] = "wonder-orb.png", // Identify Orb
        [209] = "tm.png", // Vacuum-Cut
        [210] = "wonder-orb.png", // Reviver Orb
        [211] = "wonder-orb.png", // Shocker Orb
        [212] = "wonder-orb.png", // Sizebust Orb
        [213] = "wonder-orb.png", // One-Room Orb
        [214] = "wonder-orb.png", // Fill-In Orb
        [215] = "wonder-orb.png", // Trapper Orb
        [216] = "wonder-orb.png", // Possess Orb
        [217] = "wonder-orb.png", // Itemizer Orb
        [218] = "wonder-orb.png", // Hurl Orb
        [219] = "wonder-orb.png", // Mobile Orb
        [220] = "wonder-orb.png", // Toss Orb
        [221] = "wonder-orb.png", // Stairs Orb
        [222] = "wonder-orb.png", // Longtoss Orb
        [223] = "wonder-orb.png", // Pierce Orb
        [224] = "hm.png", // Cut
        [225] = "hm.png", // Fly
        [226] = "hm.png", // Surf
        [227] = "hm.png", // Strength
        [228] = "hm.png", // Flash
        [229] = "hm.png", // Rock Smash
        [230] = "hm.png", // Waterfall
        [231] = "hm.png", // Dive
        [232] = "link-box.png", // Link Box
        [234] = "weavile-fig.png", // Weavile Fig
        [235] = "mime-jr-fig.png", // Mime Jr. Fig
        [236] = "wonder-orb.png", // Beatup Orb
    };
}
