"""Extracts every species' level-up learnset directly from a real ROM dump.

The game stores learnsets in the `wazapara` file of the system file archive
(`gSystemFileArchive`, listed in the decomp's data/system_sbin.s as a literal
name-pointer/data-pointer table over an incbin of the ROM). The file is a SIRO
container whose content is a MoveDataFile struct (include/moves.h): a pointer to
the move-data table and a pointer to a 420-entry MoveLearnset table (index =
species ID; 0 is MONSTER_NONE, valid species are 1..419, Munchlax/420 and Decoy
always get the dummy empty learnset per GetLevelUpMoves in src/moves.c). Each
MoveLearnset holds two byte-stream pointers: level-up moves and HM/TM moves
(only level-up is extracted here). A stream is a sequence of
(varint move ID, level byte) pairs terminated by a 0x00 where a move ID would
start; the varint is DecompressMoveID's format (src/pokemon.c): one byte if
< 0x80, else the first byte (masked 0x7F) is the HIGH 7 bits and the next byte
the low 7.

Unlike the lvmp### stat tables, these streams are NOT AT-compressed -- the
varint packing is the only encoding.

Verification: the decoded Bulbasaur learnset (printed at the end) matches its
known mainline-RSE-derived learnset exactly, both move names (via the editor's
own RBMoves.txt, confirming the ROM's move numbering is the same one the save
stores) and levels (1, 4, 7, 10, 15, 15, 20, 25, 32, 39, 46). The script also
asserts, for every species, that levels are non-decreasing (the game's readers
early-out on the first level > target, which only works on sorted streams) and
that every move ID exists in RBMoves.txt.

Writes RBLearnsetData.generated.cs: a species-indexed jagged ushort[] of
alternating (moveId, level) pairs, consumed by RBLearnsets.cs.
"""

import re
import struct

DECOMP = "/home/sam/Documents/projects/pokemon/RedRescueTeamRescued"
ROM = "/home/sam/Documents/projects/pokemon/Sky-Editor/roms/Pokemon Mystery Dungeon - Red Rescue Team (U).gba"
OUT = "/home/sam/Documents/projects/pokemon/Sky-Editor/SkyEditor.SaveEditor/SkyEditor.SaveEditor/MysteryDungeon/Rescue/RBLearnsetData.generated.cs"
MOVES_TXT = "/home/sam/Documents/projects/pokemon/Sky-Editor/SkyEditor.SaveEditor/SkyEditor.SaveEditor/Resources/en/RBMoves.txt"
POKEMON_TXT = "/home/sam/Documents/projects/pokemon/Sky-Editor/SkyEditor.SaveEditor/SkyEditor.SaveEditor/Resources/en/RBPokemon.txt"

NUM_LEARNSETS = 420  # entries in sMoveLearnsets; valid species IDs are 1..419


def load_ini(path):
    result = {}
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if "=" in line:
                key, _, value = line.partition("=")
                result[int(key)] = value
    return result


def find_wazapara_addr():
    with open(f"{DECOMP}/data/system_sbin.s") as f:
        lines = f.readlines()
    idx = next(i for i, l in enumerate(lines) if "Pointer to wazapara string" in l)
    m = re.search(r"gUnknown_([0-9A-Fa-f]+)", lines[idx + 1])
    return int(m.group(1), 16)


with open(ROM, "rb") as f:
    rom = f.read()

moves = load_ini(MOVES_TXT)
species_names = load_ini(POKEMON_TXT)

siro_off = find_wazapara_addr() - 0x08000000
assert rom[siro_off:siro_off + 4] == b"SIRO", rom[siro_off:siro_off + 4]
content_off = struct.unpack_from("<I", rom, siro_off + 4)[0] - 0x08000000
_move_data_ptr, learnsets_ptr = struct.unpack_from("<II", rom, content_off)
learnsets_off = learnsets_ptr - 0x08000000


def decode_stream(off):
    """Decode one (varint move ID, level) stream; returns [(move_id, level)]."""
    entries = []
    while rom[off] != 0:
        b = rom[off]
        off += 1
        if b & 0x80:
            move_id = (rom[off] & 0x7F) | ((b & 0x7F) << 7)
            off += 1
        else:
            move_id = b
        level = rom[off]
        off += 1
        entries.append((move_id, level))
    return entries


learnsets = [[]]  # index 0: MONSTER_NONE
empty = []
for species in range(1, NUM_LEARNSETS):
    levelup_ptr, _hmtm_ptr = struct.unpack_from("<II", rom, learnsets_off + species * 8)
    entries = decode_stream(levelup_ptr - 0x08000000)
    for move_id, _ in entries:
        assert move_id in moves, f"species {species}: move {move_id} not in RBMoves.txt"
    levels = [lvl for _, lvl in entries]
    assert levels == sorted(levels), f"species {species}: levels not sorted: {levels}"
    if not entries:
        empty.append(species)
    learnsets.append(entries)

lines = [
    "// AUTO-GENERATED by tools/build_learnsets.py -- do not hand-edit.",
    "// Level-up learnsets decoded from the wazapara file of the ROM's own system file",
    "// archive (the exact data GetLevelUpMoves in src/moves.c reads in-game). Index =",
    "// species ID (0..419); each row alternates (move ID, learn level). See the script",
    "// for the stream format and the verification performed.",
    "",
    "namespace SkyEditor.SaveEditor.MysteryDungeon.Rescue",
    "{",
    "    public static partial class RBLearnsets",
    "    {",
    "        internal static readonly ushort[][] GeneratedLevelUpMoves =",
    "        {",
]
for species, entries in enumerate(learnsets):
    flat = ", ".join(f"{m}, {l}" for m, l in entries)
    name = species_names.get(species, "?") if species > 0 else "(none)"
    summary = " ".join(f"{moves[m]}@{l}" for m, l in entries)
    comment = f" // #{species} {name}: {summary}" if entries else f" // #{species} {name}"
    body = f"new ushort[] {{ {flat} }}," if entries else "System.Array.Empty<ushort>(),"
    lines.append(f"            {body}{comment}")
lines += [
    "        };",
    "    }",
    "}",
    "",
]

with open(OUT, "w") as f:
    f.write("\n".join(lines))

total = sum(len(e) for e in learnsets)
print(f"Wrote {OUT}: {len(learnsets)} species rows, {total} learnset entries")
print(f"Species with empty learnsets: {empty}")


def pretty(species):
    return f"#{species} {species_names.get(species)}: " + " ".join(
        f"{moves[m]}@{l}" for m, l in learnsets[species])


print(pretty(1))    # Bulbasaur: expect Tackle@1 Growl@4 Leech Seed@7 ... Solarbeam@46
print(pretty(150))  # Mewtwo
print(pretty(304))  # Aron (slot 55 of the reference save)
